config/routes.rb
Leaderboard::Application.routes.draw do
  resources :teams, :submissions, :rankings
  root :to => 'rankings#index'
  match '/submissions/new', to: 'submissions#create', via: :post
end

app/models/submission.rb
class Submission < ActiveRecord::Base
  validates :problem, presence: true,
    uniqueness: { scope: :team_id,
      message: "already exists for this team"}
  belongs_to :team
  attr_accessible :team, :problem

  def self.boards
    [
      {
        title: 
          "<i>e</i>",
        description:
          "All problems &le; 20",
        query:
          self.
          select('team_id, SUM(problem) AS total').
          group('team_id').
          order('total DESC').
          having('MAX(problem) <= 20')
      },
      {
        title: 
          "<i>i</i>",
        description:
          "Some problems between 21 and 99",
        query:
          self.
          select('team_id, SUM(problem) AS total').
          group('team_id').
          order('total DESC').
          having('MAX(problem) BETWEEN 21 AND 99')
      },
      {
        title: 
          "<i>&pi;</i>",
        description:
            "Some problems &ge; 100",
        query:
          self.
          select('team_id, SUM(problem) AS total').
          group('team_id').
          order('total DESC').
          having('MAX(problem) >= 100')
          }
    ]
  end
end

app/models/team.rb
class Team < ActiveRecord::Base
  validates :name, uniqueness: true
  has_many :submissions

  attr_accessible :id, :name

  def problems_solved
    Submission.where(team_id: self).order(:problem).pluck(:problem)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController
  def index
    @boards = Submission.boards
    @teams = Team.all
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  def show
    @submission = Submission.find params[:id]
    redirect_to edit_submission_path @submission
  end

  def index
    @submissions = Submission.all
  end
  
  def new
    # default
  end
  
  def create
    team = Team.find_by_id(params[:new_submission][:team])
    problem = params[:new_submission][:problem]
    @submission = Submission.create!({team: team, problem: problem})
    flash[:notice] = "Submission #{@submission.team.name}/#{@submission.problem} has been added."
    if URI(request.referer).path == new_submission_path
      redirect_to new_submission_path
    else
      redirect_to submissions_path
    end
  end
  
  def edit
    @submission = Submission.find params[:id]
  end
  
  def update
    @submission = Submission.find params[:id]	
    before = "#{@submission.team.name} / #{@submission.problem}"
    team = Team.find_by_id(params[:submission][:team])
    problem = params[:submission][:problem]
    @submission.update_attributes!({team: team, problem: problem})
    after = "#{@submission.team.name} / #{@submission.problem}"
    flash[:notice] = "Was #{before}; now #{after}."
    redirect_to edit_submission_path @submission
  end
  
  def destroy
    @submission = Submission.find(params[:id])
    name = @submission.team.name
    problem = @submission.problem
    if @submission.destroy
      flash[:notice] = "Submission #{name}/#{problem} has been deleted."
    else
      flash[:notice] = "Submission #{name}/#{problem} WAS NOT DELETED!"
    end
    redirect_to submissions_path
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def show
    @team = Team.find params[:id]
    redirect_to edit_team_path @team
  end
  
  def index
    @teams = Team.all
  end

  def new
  end  

  def create
    @team = Team.create!(params[:new_team])
    flash[:notice] = "#{@team.name} has been added."
    redirect_to teams_path
  end

  def edit
    @team = Team.find params[:id]
  end
  
  def update
    @team = Team.find params[:id]	
    before = "#{@team.name}"
    @team.update_attributes!(params[:team])
    after = "#{@team.name}"
    flash[:notice] = "Team name changed: was #{before}; now #{after}."
    redirect_to edit_team_path @team
  end
  
  def destroy
    @team = Team.find(params[:id])

    Submission.where(team_id: @team).each do |s|
      s.destroy
    end
    
    name = @team.name
    if @team.destroy and 
      flash[:notice] = "Team #{name} has been deleted."
    else
      flash[:notice] = "Team #{name} WAS NOT DELETED!"
    end
    redirect_to teams_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Euler Sprint Scores
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    %meta{name: 'viewport', content: 'width=500'}
  %body
    - if flash[:notice]
      #notice.message= flash[:notice]
    - elsif flash[:warning]
      #warning.message= flash[:warning]
    = yield

app/views/rankings/_rankings.html.haml
%div.rankings_container
  - @boards.each do |board|
    %div.ranking
      %h2!= board[:title]
      %p!= board[:description]
      %table.board
        %thead
          %tr
            %th= # blank for CSS tr::before counter
            %th Team name
            %th Score
        %tbody
          - board[:query].each do |row|
            %tr
              %td= "#{row.team.name} #{row.team.problems_solved}"
              %td<= row.total
      %code= board[:query].to_sql

app/views/rankings/index.html.haml
%h1 Rankings
= render 'rankings'
%h2= link_to 'Submissions', submissions_path

app/views/submissions/_all_submissions.html.haml
%table#solved_problems
  %thead
    %tr
      %th Team name
      %th Problem
  %tbody
    - @submissions.each do |submission|
      %tr
        %td= submission.team.name
        %td= submission.problem
        %td= link_to 'edit', submission_path(submission.id)

app/views/submissions/_form.html.haml
=form_for form do |f|
 %table
  %tr
   %th Team
   %td=f.collection_select(:team, Team.all, :id, :name)
  %tr
   %th Problem
   %td
    =f.number_field :problem, {placeholder: 'Problem number'}
  %tr
   %th
   %td=f.submit

app/views/submissions/edit.html.haml
%h1 #{@submission.team.name} / #{@submission.problem}
%h2 Edit submission
= render partial: 'form', object: @submission

%h2 Delete submission
= button_to 'Delete submission', submission_path(@submission), :method => :delete, :confirm => 'Are you sure?'

%h2= link_to 'Edit team', team_path(@submission.team)
%h2= link_to 'Submissions', submissions_path
%h2= link_to 'Rankings', rankings_path

app/views/submissions/index.html.haml
%h1 Submissions

%h2 New submission

= render partial: 'form', object: :new_submission

%h3= link_to 'Simple add interface', new_submission_path

%h2 Solved problems

= render 'all_submissions'

%h2= link_to 'Rankings', rankings_path
%h2= link_to 'Teams', teams_path

app/views/submissions/new.html.haml
%h2 New submission

= render partial: 'form', object: :new_submission

%h2= link_to 'Submissions', submissions_path
%h2= link_to 'Rankings', rankings_path
%h2= link_to 'Teams', teams_path